// <auto-generated />
namespace websitequanlutours.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _111rrrr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_111rrrr));
        
        string IMigrationMetadata.Id
        {
            get { return "202304251933476_111rrrr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
